name: MLOps-demo
on:
  push:
    paths:
      - "back-end/**"
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        run: |
          python back-end/test.py
